name: Python application on self-hosted

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python in a virtual env
      run: |
        if [[ `uname` != "Darwin" ]]; then sudo apt -y install python3-venv; fi
        python3 -m venv .env

    - name: Install dependencies
      run: |
        source .env/bin/activate
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: run test
      run: |
        python3 test.py
